In [5]:
import os
import pandas as pd

raw_path = "../data/raw"
files = os.listdir(raw_path)
print(files)

['AQI Bangladesh.csv', 'cities.csv']

In [8]:
aqi = pd.read_csv(os.path.join(raw_path, "AQI Bangladesh.csv"))
cities = pd.read_csv(os.path.join(raw_path, "cities.csv"))

print("AQI:", aqi.shape)
print("Cities:", cities.shape)

AQI: (1048551, 13)
Cities: (103, 4)

In [9]:
print(aqi.columns.tolist())
aqi.head()

['city_id', 'city_name', 'lat', 'lon', 'datetime', 'pm10', 'pm2_5', 'carbon_monoxide', 'carbon_dioxide', 'nitrogen_dioxide', 'sulphur_dioxide', 'ozone', 'aqi']

,city_id,city_name,lat,lon,datetime,pm10,pm2_5,carbon_monoxide,carbon_dioxide,nitrogen_dioxide,sulphur_dioxide,ozone,aqi
0,7701354,Azimpur,23.7298,90.3854,2022-08-05T00:00,25.0,16.7,252.0,NaN,18.6,5.2,13.0,50.0
1,7701354,Azimpur,23.7298,90.3854,2022-08-05T01:00,18.5,12.3,249.0,NaN,18.5,5.7,19.0,50.0
2,7701354,Azimpur,23.7298,90.3854,2022-08-05T02:00,16.1,10.9,244.0,NaN,18.4,6.5,27.0,51.0
3,7701354,Azimpur,23.7298,90.3854,2022-08-05T03:00,15.4,10.3,233.0,NaN,17.2,6.9,39.0,51.0
4,7701354,Azimpur,23.7298,90.3854,2022-08-05T04:00,16.8,11.3,217.0,NaN,14.8,6.2,51.0,51.0

In [10]:
print(cities.columns.tolist())
cities.head()

['ID', 'Name', 'Latitude', 'Longitude']

   ID      Name  Latitude  Longitude
0   1   Rangpur  25.74664   89.25166
1   2   Sherpur  25.01881   90.01751
2   3  Dinājpur  25.62745   88.63779
3   4   Lākshām  23.24018   91.12143
4   5   Comilla  23.46186   91.18503

In [11]:
aqi.info()
print(aqi.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 1048551 entries, 0 to 1048550
Data columns (total 13 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   city_id           1048551 non-null  int64
 1   city_name         1048551 non-null  str
 2   lat               1048551 non-null  float64
 3   lon               1048551 non-null  float64
 4   datetime          1048551 non-null  str
 5   pm10              1048551 non-null  float64
 6   pm2_5             1048551 non-null  float64
 7   carbon_monoxide   1048551 non-null  float64
 8   carbon_dioxide    274224 non-null   float64
 9   nitrogen_dioxide  1048551 non-null  float64
 10  sulphur_dioxide   1048551 non-null  float64
 11  ozone             1048551 non-null  float64
 12  aqi               1047855 non-null  float64
dtypes: float64(10), int64(1), str(2)
memory usage: 128.6 MB
city_id                  0
city_name                0
lat                      0
lon                      0
datetime                 0
pm10                     0
pm2_5                    0
carbon_monoxide          0
carbon_dioxide      774327
nitrogen_dioxide         0
sulphur_dioxide          0
ozone                    0
aqi                    696
dtype: int64